### ISSUE TITLE
Mic/camera access dialogs prevent video from showing

### ISSUE THREAD

**Issue by mattdeckard** [webex/spark-ios-sdk#36]
We recently updated our SparkSDK pod to point to the latest `develop` branch, to get some as-of-yet unreleased fixes. We noticed after doing this that when you try to make a video call for the first time, when the app prompts to allow microphone and camera access, the video will never start properly.

We have worked around this by calling `AVCaptureDevice.requestAccess` prior to attempting the video call, but we still wanted to let you know this appears to be a regression currently in your `develop` branch.

**Comment by Noble-Six** [comment]
It seems there have some issues on media engine when prompts camera access.
Out media engine team are dealing with this problem.
When they fix it and release a new version, we will update the engine binary ASAP.

**Comment by olivierproffit** [comment]
@mattdeckard I think it's solved, so I am closing it but feel free to ping me over Webex Teams (oproffit@cisco.com) to further discuss if needed.
