### ISSUE TITLE
Refresh token in iOS Spark Integration.

### ISSUE THREAD

**Issue by suneethchakravarthy** [webex/spark-ios-sdk#42]
I have integrated Spark SDK into an iOS application. I have done authorization and am able to perform Spark features (i.e., Sending message, Video Calling, Creating Room, etc..)
 
I have done the authorization using SDK as follows.
 
   **let authenticator = OAuthAuthenticator(clientId: clientId, clientSecret: clientSecret, scope: scope, redirectUri: redirectUri)
    let spark = Spark(authenticator: authenticator)
 
    if !authenticator.authorized {
      authenticator.authorize(parentViewController: self) { success in
        if !success {
          print("User not authorized")
        }
     }
    }**
 
 
Do we have to do any additional implementation for **refreshToken** functionality? Or Will Spark SDK will take care of refreshing token from background?
Please guide me through the steps if we need to refresh the token explicitly.

**Comment by kliu** [comment]
Spark SDK will do the refreshToken functionality when needed in the background.

And if the refresh also fails, there is an optional API (`OAuthAuthenticatorDelegate.refreshAccessTokenFailed`) to notify the app.

**Comment by olivierproffit** [comment]
@suneethchakravarthy does it work for you? I am closing it but feel free to ping me over Webex Teams (oproffit@cisco.com) to further discuss if needed.
