### ISSUE TITLE
Use latest version of ObjectMapper and SwiftyJSON

### ISSUE THREAD

**Issue by JosselinOudry** [webex/spark-ios-sdk#45]
Hi there,

As per the podspec these two pods are stuck to old versions:
s.dependency 'ObjectMapper', '~> 2.0'
s.dependency 'SwiftyJSON', '~> 3.0'

Whereas the most recent versions of these pods are as such:
ObjectMapper (3.1.0)
SwiftyJSON (4.0.0)

Our mobile app needs to use those pods latest versions.

Is there a plan to update spark-ios-sdk accordingly?

Thanks in advance.

**Comment by jfield44** [comment]
Same issue here, can we get the Podspec updated?

**Comment by qucui** [comment]
Sorry for the late reply, we have pushed a hotfix-#45 branch on our git, which implemented ObjectMapper(3.1.0) and  SwiftyJSON(4.0.0). 

You could fetch this pod  branch to resolve this issue:
pod ’SparkSDK’, :git => 'https://github.com/ciscospark/spark-ios-sdk',:branch => ‘Hotfix-#45’

Now we are considering to upgrade our sdk's pod dependency and swift 4.0 supporting on next release. 

If you have compiling error using Swift 4.0, 
try:
Project->pods->targets->SparkSDK->BuildSetting->Swift Language Version, select to the Swift 3.2
Project->pods->targets->ObjectMapper->BuildSetting->Swift Language Version, select to the Swift 3.2

**Comment by ciauri** [comment]
In order to reduce complexity and dependencies, would Codable be a roadmap item for this project?

**Comment by qucui** [comment]
We released SDK version 1.4 witch supports ObjectMapper(3.1.0) and SwiftyJSON(4.0.0)
