### ISSUE TITLE
Server-side support

### ISSUE THREAD

**Issue by zdnk** [webex/spark-ios-sdk#48]
It would be awesome to be able to use the SDK for building bots etc. at server side :)

**Comment by olivierproffit** [comment]
@zdnk for server side, we have more suitable SDKs:
- https://developer.webex.com/docs/sdks/node
- https://developer.webex.com/docs/sdks/java
- https://developer.webex.com/docs/sdks/community

**Comment by olivierproffit** [comment]
@zdnk I am closing it but feel free to ping me over Webex Teams (oproffit@cisco.com) to further discuss if needed.
