### ISSUE TITLE
How to use screenShareView

### ISSUE THREAD

**Issue by MrShiY** [webex/spark-ios-sdk#52]
This 'screenShareView' didn't show anything, How can I use it when posting or receiving?

**Comment by MrShiY** [comment]
What you said is very clear, Thank you very much. A bold question, where are you from ?

**Comment by Noble-Six** [comment]
Hi @MrShiY, We are Cisco Spark [Beijing](https://en.wikipedia.org/wiki/Beijing) Team :smile:

**Comment by MrShiY** [comment]
那好吧,咱说点利索的语音,ARKit能通过你们的视频回话传递过去不?

**Comment by Noble-Six** [comment]
现在只能把屏幕的帧数据传过去。SDK内部没有AR相关的特性。实际上底层是可以接收任意视频帧数据传给远端的，只是目前没有开放用户直接传视频帧的接口。
音频的话目前还不清楚底层库有没有传自定义数据的接口。
后续有需求会添加AR相关的需求，或者直接开放灵活性更高的传帧接口。这个还要和PM讨论。

**Comment by MrShiY** [comment]
你指的是把AR录制成视频,然后实时传过去?其实ARKit提供了每一帧的Image,能用上吗?

**Comment by Noble-Six** [comment]
可以的，screen share 也是用的系统提供的视频帧数据。
如果以后放开传视频帧的接口的话，这个功能就能实现了，底层是支持的。

**Comment by MrShiY** [comment]
好的.我等你们开放这个接口哦,Android已经开放了. Thanks, friend.
