### ISSUE TITLE
Compiler warning Seu.framework umbrella header

### ISSUE THREAD

**Issue by rikvdbrule** [webex/spark-ios-sdk#58]
In version 1.4, when importing the SparkSDK, the Swift compiler generates the following warning messages:

```
<#Project directory#><module-includes>:1:1: Umbrella header for module 'Seu' does not include header 'NSData+Extensions.h'

<#Project directory#><module-includes>:1:1: Umbrella header for module 'Seu' does not include header 'KmsEphemeralKeyRequest+Private.h'

<#Project directory#><module-includes>:1:1: Umbrella header for module 'Seu' does not include header 'CjoseWrapper+Private.h'
```

These warnings occur because these headers are present in the Headers directory of the Seu.framework within the SparkSDK Pods project, but are not included in the `Seu.h` umbrella header. The issue can be replicated by building the latest version of the KitchenSink demo app. 

The issue seems relatively simple to fix (either remove the headers from the public Header directory, or add them to the umbrella header), but because the framework is not open for outside collaborators I cannot submit a pull request.

**Comment by qucui** [comment]
@rikvdbrule thanks for the suggests, we've already fixed it, and pushed to the develop branch. Will merger it into master on next release.
