### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported in Swift 4.2

### ISSUE THREAD

**Issue by al1k0s** [webex/spark-ios-sdk#61]
it is happening when developing with Xcode10.

if i manually add 4.1.2 toolchain then it builds but crashes at start

error: invalid value path 'symbols.clang-modules-cache-path'

**Comment by al1k0s** [comment]
error: invalid value path 'symbols.clang-modules-cache-path'
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/alik/Library/Developer/CoreSimulator/Devices/92EBB976-A09C-4173-B637-F28CA40CE1C6/data/Containers/Bundle/Application/2EFF1CFE-AA3B-4894-B6C7-7911B160FA10/Spark.app/Frameworks/Sbu.framework/Sbu
  Reason: Incompatible library version: Sbu requires version 1.0.0 or later, but libswiftAVFoundation.dylib provides version 0.0.0

**Comment by Noble-Six** [comment]
Hi @al1k0s, thank you for your report this issue.  Will be fixed in 2.0 version https://github.com/webex/webex-ios-sdk

**Comment by hawk-ukr** [comment]
@Noble-Six hi, i have same issue, can you please clarify what are your plans on release v2.0 with this fix?

**Comment by Noble-Six** [comment]
Hi @hawk-ukr, discussed with our team, we plan to release a patch for 1.4 next week. 
2.0 also will EFT next week if everything goes well.

**Comment by hawk-ukr** [comment]
@Noble-Six good news, thank you

**Comment by Noble-Six** [comment]
Hi @al1k0s @hawk-ukr, We have released 1.4.1 to support Swift4.2.
Thank you for your patience. Please let us know if this works for you!

**Comment by al1k0s** [comment]
@Noble-Six Everything works, thanks. Waiting til 2.0 release!

**Comment by Noble-Six** [comment]
@al1k0s we will delay the 2.0 release because of the web services platform upgrade&maintain. I'm not sure the GA date. Please watch this repo:https://github.com/webex/webex-ios-sdk to catch up our progress on 2.0. Thanks

**Comment by Noble-Six** [comment]
Close issue.
